### ISSUE TITLE
Seriously doubtful

### ISSUE THREAD

**Issue by opentld** [taki0112/UGATIT#43]
After a few days of testing, I cannot help doubting this algorithm. Is it as good as the paper claims? Why not release a pre-trained model for everyone to test? Seriously doubtful!

@taki0112

**Comment by taki0112** [comment]
1. We released [**50 epoch**](https://drive.google.com/file/d/1V6GbSItG3HZKv3quYs7AP0rr1kOCT3QO/view) and [**100 epoch**](https://drive.google.com/file/d/19xQK2onIy-3S5W5K-XIh85pAg_RNvBVf/view) checkpoints so that people could test more widely.
2. Also, We published [**the selfie2anime datasets**](https://drive.google.com/file/d/1xOWj1UVgp6NKMT3HbPhBbtq2A4EDkghF/view) we used in the paper.

3. And, we fixed [code in **smoothing**](https://github.com/taki0112/UGATIT/blob/master/ops.py#L196)
